# Generated by Django 4.2.6 on 2023-11-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_owner_alter_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.IntegerField(default=10000, verbose_name='Цена'),
        ),
    ]
