# Generated by Django 4.2.6 on 2023-11-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payment',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
