# Generated by Django 4.2.6 on 2023-11-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_payments_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего обновления рассылки'),
        ),
    ]
